-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcig6xcpYXY99MpUA
Lshwf4yqkyqsKQGdOtcC92+1J+KgCgYIKoZIzj0DAQehRANCAAS+7COe4cMcZ65C
3F9lGfXgIa8g1oeL/nTgUpuOVN+FIIaE5NuIIL1ApENriTrGibEMW8dbOBNjWsaM
qIUSR/Qf
-----END PRIVATE KEY-----